apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tedelin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tedelin/tedelin_iot.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
